ExchangeView folder
Olexantor/Exchange pull request #24
Opened 2022-03-30 09:57 UTC by Olexantor

removed Rx sequences and implemented first screen logic with closures

2022-03-30 10:25 UTC, nchlscs requested changes

2022-03-30 10:25 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewController.swift
>  import UIKit
Почисти лишние зависимости в файлах

2022-03-30 10:25 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewController.swift
> +        UserDefaults.standard.removeObject(forKey: "currencies")
А это что делает?

2022-03-30 10:25 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +import UIKit
В модели не может быть юайкита, постарайся без него обойтись. И тоже лишние зависимости

2022-03-30 10:25 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
>      struct Inputs{
Пустую структуру можно удалить, если не используешь

2022-03-30 10:52 UTC, Olexantor commented on Exchange/ExchangeView/ExchangeViewController.swift
>  import UIKit
почистил

2022-03-30 10:55 UTC, Olexantor commented on Exchange/ExchangeView/ExchangeViewController.swift
> +        UserDefaults.standard.removeObject(forKey: "currencies")
этот метод чистит   userDef, иногда мне это нужно чтобы увидеть процесс похода в сеть

2022-03-30 10:55 UTC, Olexantor commented on Exchange/ExchangeView/ExchangeViewController.swift
> +        UserDefaults.standard.removeObject(forKey: "currencies")
удалил его тоже

2022-03-30 10:56 UTC, Olexantor commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +import UIKit
переделал без кита но чуть-чуть логики из-за этого стало в контроллере

2022-03-30 10:56 UTC, Olexantor commented on Exchange/ExchangeView/ExchangeViewModel.swift
>      struct Inputs{
удалил

2022-03-31 08:53 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewController.swift
> +    private var buttonNumber: ButtonNumberInOrder!
А зачем тебе это хранить глобально в контроллере?

2022-03-31 08:53 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewController.swift
> +        UserDefaults.standard.removeObject(forKey: "currencies")
Тогда наверное имеет смысл сделать какую-то абстракцию, отвечающую за локальное хранение данных, и в зависимости от нужд через `Dependencies` прокидывать в экран либо реальные `UserDefaults`, либо пустышку. Сможешь сделать такое?

2022-03-31 08:58 UTC, nchlscs requested changes

2022-03-31 08:58 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +import UIKit
Все равно есть юайкит в модели

2022-03-31 08:58 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +    private static var ratesForFirstCurrency = [String: Double]()
Так хранить можно, но лучше отдельно от публичных свойств, чтобы не мелькали. Вынеси в приватное расширение, например

2022-03-31 08:58 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +        var textFieldDidChange: (TextFieldID, UITextField) -> Void = { _,_  in }
Модель знает о существовании какого-то `UITextField`, а не должна

2022-03-31 08:58 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +        func getRates(for currency: String, by buttonNumber: ButtonNumberInOrder) {
Вложенные функции по возможности лучше не использовать, вынеси ее в приватное расширение и сделай статической

2022-03-31 09:02 UTC, nchlscs commented on Exchange/ExchangeView/ExchangeViewModel.swift
> +        func getRates(for currency: String, by buttonNumber: ButtonNumberInOrder) {
Либо, если хочешь оставить тут, то переделай на замыкание. На твое усмотрение

2022-03-31 11:59 UTC, nchlscs approved these changes

2022-03-31 12:08 UTC, nchlscs approved these changes

2022-03-31 12:14 UTC, merged