Injection rx swift
Olexantor/Exchange pull request #25
Opened 2022-04-11 10:46 UTC by Olexantor

2022-04-11 11:40 UTC, nchlscs requested changes

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewController.swift
> +            searchCurrency: searchController.searchBar.rx.text.asDriver()
Наверное, это все-таки `searchText`
```suggestion
            searchText: searchController.searchBar.rx.text.asDriver()
```

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewController.swift
> +            })
Если уже разобрался, что происходит под капотом, то рекомендую привыкать к короткой записи

```suggestion
            .drive(cellViewModels)
```

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +        let cellViewModels = BehaviorRelay<[CurrencyCellViewModel]>(value: [])
Предлагаю назвать как-то вроде `filteredViewModels`, чтобы сразу была очевидна разница между этим и `allViewModels`

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
>          if let listOfCurrency = dependency.storageService.unloadCurrency() {
А сможешь `storageService` тоже обернуть в реактивную оболочку? 
Чтобы его методы выглядели так: `unloadCurrency() -> Single<[String]>`

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
>          } else {
Так наверное лучше не делать, можно на момент вызова `fetchCurrencyList()` проверять, получены ли данные из хранилища или нет (тоже в рамках цепочки), и если не получены, то уже дергать сетевой метод. И это бы избавило от костыля с постепенным заполнением `disposables`, как у тебя сейчас. Подумай, как сделать

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                router.showAlert()
Показывай конкретную ошибку, которая пришла

2022-04-11 11:40 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                let filteredModels = allViewModels
Создаешь константу и тут же возвращаешь ее. Может, сразу возвращать?

2022-04-11 11:55 UTC, Olexantor commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                let filteredModels = allViewModels
да я думал для читабельности так сделать) исправил

2022-04-11 11:55 UTC, Olexantor commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                router.showAlert()
исправил

2022-04-11 11:55 UTC, Olexantor commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +        let cellViewModels = BehaviorRelay<[CurrencyCellViewModel]>(value: [])
исправил

2022-04-11 11:56 UTC, Olexantor commented on Exchange/SelectCurrencyView/SelectCurrencyViewController.swift
> +            })
да, понимать стал вроде, исправил

2022-04-11 13:29 UTC, Olexantor commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
>          if let listOfCurrency = dependency.storageService.unloadCurrency() {
переделал

2022-04-11 13:56 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                        .emit(to: filteredViewModels)
Ты в конечном замыкании `subscribe` создаешь еще одну подписку, которая нигде не хранится, отсюда предупреждение. Так делать нельзя, если твоя цепочка должна по каким-то условиям превратиться в другую цепочку, то нужно использовать оператор `flatMapLatest`

2022-04-11 13:56 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
> +                        .emit(to: filteredViewModels)
И ты в рамках одной цепочки в двух местах присваиваешь значение в `filteredViewModels`, а лучше бы в одном. Опять же, `flatMapLatest` тут поможет

2022-04-11 13:56 UTC, nchlscs commented on Exchange/SelectCurrencyView/SelectCurrencyViewModel.swift
>              })
```suggestion
            .emit(onNext: router.showAlert)
```

2022-04-12 05:10 UTC, nchlscs approved these changes

2022-04-12 05:11 UTC, merged